### ISSUE TITLE
if destination dir has existed,  will throw error with status 128 

### ISSUE THREAD

**Issue by zimplexing** [flipxfx/download-git-repo#25]
running many times  will throw err 
```js
download('bitbucket:flipxfx/download-git-repo-fixture#my-branch', 'test/tmp', { clone: true }, function (err) {
  console.log(err ? 'Error' : 'Success')
})
```
**ERROR**
```JS
Error: 'git clone' failed with status 128
    at ChildProcess.<anonymous> (G:\prediction\vue-open-dev\node_modules\git-clone\index.js:33:22)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

**Comment by flipxfx** [comment]
This seems like the intended behavior. This repo should never try to delete anything to make sure the downloads work correctly, that's up to the parent repo/user.

**Comment by zimplexing** [comment]
thx
